services:    
  data-producer:
    image: data-producer
    build:
      context: .
      dockerfile: src/Modules/DataProducer/Dockerfile

  datetimespammer-grpc-server:
    image: datetimespammer-grpc-server
    build:
      context: .
      dockerfile: src/Modules/DateTimeSpammer.gRPC.Server/Dockerfile